services:
  - type: web
    name: globalline-backend
    env: docker
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: globalline-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: globalline-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: globalline-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: globalline-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: globalline-db
          property: password
    region: oregon
    plan: free

databases:
  - name: globalline-db
    databaseName: globalline
    user: globalline
    plan: free
    region: oregon
